spring.application.name=analytics-admin-service
server.port=${PORT:8084}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:analytics_admin_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.serialization.indent_output=true